import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {ReactQueryClientProvider} from "@/components/ReactQueryClientProvider";
import {AuthProvider, useAuth} from "@/components/AuthContext";
import {Header} from "@/components/ui/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ReactQueryClientProvider>
        <AuthProvider>
            <html lang="en">
            <body className="min-h-screen bg-slate-100 text-slate-900">
            <Header/>
            <main className="max-w-3xl mx-auto px-4 py-8">
                {children}
            </main>
            </body>
            </html>
        </AuthProvider>
    </ReactQueryClientProvider>
  );
}
